- name: "0 - Backlog"
  color: "CCCCCC"
  description: "Issue is accepted, but is not ready to be worked on or not in current sprint."
- name: "0 - Triaging"
  color: "EEEEEE"
  description: "Issue is accepted, but a milestone has yet to be added for the issue."
  aliases: ["triage", "_triage", "0 - _Triaging"]
- name: "0 - Waiting on User"
  color: "AABBDD"
  description: "Insufficient information for issue or PR, issue may be closed if no response from user."
- name: "1 - Ready"
  color: "CCCCCC"
  description: "Issue is accepted, milestone added and are ready to be worked on."
- name: "2 - Working"
  color: "CCCCCC"
  description: "A user or team member has started working on the issue."
- name: "3 - Review"
  color: "CCCCCC"
  description: "Code has been added, and is available for review as a pull request."
- name: "4 - Done"
  color: "CCCCCC"
  description: "Code has been added to the repository, and has been reviewed by a team member."
- name: "5 - Released"
  color: "CCCCCC"
  description: "The issue has been resolved, and released to the public for consumption."
- name: "5 - Fixed Upstream"
  color: "CCCCCC"
  description: "The issue has been resolved in an upstream project meaning this issue can also be resolved."
- name: "ADD AUTO TESTS"
  color: "8E44AD"
  description: "Things that typically go to Test-Kitchen - once completed, IN REGRESSION TEST SUITE label added."
- name: "ADD MANUAL TESTS"
  color: "8E44AD"
  description: "Manual tests has not been added for issue - once completed, IN MANUAL TEST SUITE label added."
- name: "API"
  color: "207DE5"
  description: "Issues that handles API changes, not necessarily visible to end users."
- name: "Bad Pull Request"
  color: "EB6420"
  description: "The pull request opened was not accepted, didn't follow the procedures, or was missing information."
- name: "Blocked - External"
  color: "5319E7"
  description: "The issue or pull request is not fixable without a change in a upstream/external library."
- name: "Breaking Change"
  color: "5319E7"
  description: "The issue will introduce backwards incompatible changes."
  aliases: ["BreakingChange"]
- name: "Bug"
  color: "D73A4A"
  description: "Issues where something has happened which was not expected or intended."
- name: "Build Automation"
  color: "0052CC"
  description: "Issues for changes to the build system, without functional changes needed to the project."
  aliases: ["BuildAutomation", "Build"]
- name: "CoreTeam"
  color: "F7C6C7"
  description: "Issues that will only be accepted from the core Chocolatey Team."
- name: "Customer"
  color: "006B75"
  description: "Bug reported or feature requested by a licensed customer of Chocolatey."
- name: "Detail Required"
  color: "9C772F"
- name: "Documentation"
  color: "BFE5BF"
  description: "Issues for changes that only need to change documentation."
- name: "Duplicate Issue"
  color: "EB6420"
  description: "Issues that are duplicates of other issues."
  aliases: ["duplicate", "duplicates"]
- name: "Enhancement"
  color: "5319E7"
  description: "Issues that introduce new functionality to the project, or enhances/updates existing functionality."
  aliases: ["FeatureParity, Feature, Improvement"]
- name: "Deprecate"
  color: "2F1E3B"
  description: "Features or functionality that is being deprecated in favor of removing or replacing them in future."
- name: "Hacktoberfest"
  color: "FB9904"
  description: "Issues opened during hacktoberfest."
- name: "hacktoberfest-accepted"
  color: "1D76DB"
  description: "Pull Requests opened during hacktoberfest, and has been accepted by a team member."
- name: "Has Dependency"
  color: "8E44AD"
  description: "This issue has a related issue that would need to be addressed before this issue can be closed."
  aliases: ["Has related issue", "HasDependency"]
- name: "IN MANUAL TEST SUITE"
  color: "8E44AD"
  description: "These are things that are documented to test as part of a release."
- name: "Dependency Change"
  color: "888F21"
  description: "If a dependency or bundled binaries are added, removed or updated."
- name: "IN REGRESSION TEST SUITE"
  color: "8E44AD"
  description: "These are things that are handled by tools like Test-Kitchen."
- name: "Invalid / Not Issue / No repro / Not Implementing"
  color: "EB6420"
  aliases: ["wontfix", "Wrong Repository"]
- name: "invalid"
  color: "E89819"
  description: "This is used to mark Hacktoberfest PR's as invalid."
- name: "NO RELEASE NOTES"
  color: "CCCCCC"
  description: "Should not be included in the release notes - not enhancing or fixing end product."
- name: "No Response / Stale"
  color: "EB6420"
  description: "Used on issues when additional information is requested, and no response has been given."
- name: "Pending Closure"
  color: "EB6420"
  description: "This issue has been marked as having no response or is stale and will soon be closed."
- name: "Priority - Urgent"
  color: "F52200"
  description: "Represents issues that are of urgent priority, and should be dealt with first."
- name: "Priority - High"
  color: "FBCC01"
  description: "Represent high priority tickets - things that must be addressed soon."
  aliases: ["Priority_HIGH"]
- name: "Priority - Normal"
  color: "6FDDFF"
  description: "Represents issues that are of normal priority."
- name: "Priority - Low"
  color: "D8D8D8"
  description: "Represents issues that are of lower priority, can be taken care of whenever."
  aliases: ["Priority_LOW"]
- name: "Pro/Business"
  color: "006B75"
  description: "Issues only relevant for Pro or Business customers."
- name: "Question"
  color: "EB6420"
  description: "Issues opened for asking questions. These should be converted to discussions."
- name: "Requires Upstream Change"
  color: "E10D60"
  description: "Requires changes to a different location once issue is fixed or implemented."
- name: "Security"
  color: "5319E7"
  description: "Issues that are related to security vulnerabilities, or other security related problems."
  aliases: ["security vulnerability"]
- name: "WorkItem"
  color: "006B65"
  description: "Non-bug, non-feature related things. Could be refactoring. Sometimes non-code related things."
  aliases: ["TaskItem"]
- name: "Tests"
  color: "421772"
  description: "Issues related to the tests (NUnit, xUnit, Pester, etc)."
- name: "Top Issues Dashboard"
  color: "#027E9D"
  description: "Top issues dashboard."
- name: "Up For Grabs"
  color: "159818"
  description: "Issues that are available by the community to work on."
  aliases: ["good first issue", "help wanted"]
- name: "Area - Refactor"
  color: "9400D3"

  description: "Issues that represent refactoring code for maintainability."
